### ISSUE TITLE
version 1.20 no longer works

### ISSUE THREAD

**Issue by mx1002** [Twilight0/plugin.video.alphatv.gr#2]
Hello, I cannot view alpha series .  
For example  last episode of 'Ελληνοφρενια' can be viewed via VLC:

rtmp://193.92.37.231:1935/AlphaEdge/_definst_/mp4:path2/2017-2018/microsites/ellinofreneia/ELLHNOFRENEIA_S05_EP04_.mp4.mp4?aLphATvQu3r7pendtime=1512289563&aLphATvQu3r7pstarttime=1512271563&aLphATvQu3r7phash=jh6reNM8JcZL-bmxbf_ZCWYbKV5lehZe0_wFKZzV7Z8=

But not via Kodi 17.6 (tested both on PC and Android)

Error Log:
==========================================================
06:16:18.308 T:6732  NOTICE: VideoPlayer: Opening: http://193.92.37.231:1935/AlphaEdge/_definst_/mp4:path2/2017-2018/microsites/ellinofreneia/ELLHNOFRENEIA_S05_EP02_.mp4.mp4/manifest.mpd?aLphATvQu3r7pendtime=1512288985&aLphATvQu3r7pstarttime=1512270985&aLphATvQu3r7phash=J22z8kp5Jqsh1fKJuw-_1D6Y-PwbryiVy2waWOM4_lI=
06:16:18.309 T:6732 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
06:16:18.367 T:6732 WARNING: DXVA::CProcessorHD::PreInit: failed to get video device.
06:16:18.367 T:6732  NOTICE: CWinRenderer::Preinit - could not init DXVA processor - skipping
06:16:18.367 T:6724  NOTICE: Creating InputStream
06:16:18.541 T:6724  NOTICE: Creating Demuxer
06:16:18.651 T:6724   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, http://193.92.37.231:1935/AlphaEdge/_definst_/mp4:path2/2017-2018/microsites/ellinofreneia/ELLHNOFRENEIA_S05_EP02_.mp4.mp4/manifest.mpd?aLphATvQu3r7pendtime=1512288985&aLphATvQu3r7pstarttime=1512270985&aLphATvQu3r7phash=J22z8kp5Jqsh1fKJuw-_1D6Y-PwbryiVy2waWOM4_lI=
06:16:18.651 T:6724   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
06:16:18.651 T:6724  NOTICE: CVideoPlayer::OnExit()
06:16:18.651 T:6732   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.alphatv.gr/?action=play&url=http%3A%2F%2Fwww.alphatv.gr%2Fshows%2Fentertainment%2Fellinofreneia%2Fwebtv%2F141117&image=http%3A%2F%2Fwww.alphatv.gr%2Fsites%2Ftv%2Ffiles%2Fstyles%2Falpha_carousel_thumb_v2%2Fpublic%2Fvideo-thumbs%2Fvlcsnap-2017-11-15-10h51m39s406.png%3Fitok%3DHsLmjmGR%26c%3Df8741db48ca943af946409f5f99dc4a7&title=14%2F11%2F17]
06:16:18.664 T:6732  NOTICE: CVideoPlayer::CloseFile()
06:16:18.664 T:6732  NOTICE: VideoPlayer: waiting for threads to exit
06:16:18.664 T:6732  NOTICE: VideoPlayer: finished waiting
06:16:18.664 T:6732  NOTICE: CVideoPlayer::CloseFile()
06:16:18.664 T:6732  NOTICE: VideoPlayer: waiting for threads to exit
06:16:18.664 T:6732  NOTICE: VideoPlayer: finished waiting
06:16:21.026 T:6732  NOTICE: VideoPlayer: Opening: http://193.92.37.231:1935/AlphaEdge/_definst_/mp4:path2/2017-2018/microsites/ellinofreneia/ELLHNOFRENEIA_S05_EP04_.mp4.mp4/manifest.mpd?aLphATvQu3r7pendtime=1512288987&aLphATvQu3r7pstarttime=1512270987&aLphATvQu3r7phash=AYH74IRXZj1i1oE2K7S0Q16MS0vKH8zL--_SKDLsMmw=
06:16:21.026 T:6732 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
06:16:21.084 T:6732 WARNING: DXVA::CProcessorHD::PreInit: failed to get video device.
06:16:21.084 T:6732  NOTICE: CWinRenderer::Preinit - could not init DXVA processor - skipping
06:16:21.085 T:3732  NOTICE: Creating InputStream
06:16:21.258 T:3732  NOTICE: Creating Demuxer
06:16:21.367 T:3732   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, http://193.92.37.231:1935/AlphaEdge/_definst_/mp4:path2/2017-2018/microsites/ellinofreneia/ELLHNOFRENEIA_S05_EP04_.mp4.mp4/manifest.mpd?aLphATvQu3r7pendtime=1512288987&aLphATvQu3r7pstarttime=1512270987&aLphATvQu3r7phash=AYH74IRXZj1i1oE2K7S0Q16MS0vKH8zL--_SKDLsMmw=
06:16:21.367 T:3732   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
06:16:21.367 T:3732  NOTICE: CVideoPlayer::OnExit()
06:16:21.367 T:6732   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.alphatv.gr/?action=play&url=http%3A%2F%2Fwww.alphatv.gr%2Fshows%2Fentertainment%2Fellinofreneia%2Fwebtv%2F281117&image=http%3A%2F%2Fwww.alphatv.gr%2Fsites%2Ftv%2Ffiles%2Fstyles%2Falpha_carousel_thumb_v2%2Fpublic%2Fvideo-thumbs%2Fvlcsnap-2017-11-29-10h17m40s416.png%3Fitok%3D0ImNiOwJ%26c%3D64811d503422251c22e58bd2851fbb69&title=28%2F11%2F17]
06:16:21.380 T:6732  NOTICE: CVideoPlayer::CloseFile()
06:16:21.380 T:6732  NOTICE: VideoPlayer: waiting for threads to exit
06:16:21.380 T:6732  NOTICE: VideoPlayer: finished waiting
06:16:21.380 T:6732  NOTICE: CVideoPlayer::CloseFile()
06:16:21.380 T:6732  NOTICE: VideoPlayer: waiting for threads to exit
06:16:21.380 T:6732  NOTICE: VideoPlayer: finished waiting
06:16:25.901 T:5464   ERROR: ADDON: extension '' is not currently supported for service addon
06:16:49.489 T:3724   ERROR: Previous line repeats 8 times.

**Comment by Twilight0** [comment]
Fixed in version 1.2.1 which will be uploaded in a few moments.
