### ISSUE TITLE
v. 1.21 doesn't work

### ISSUE THREAD

**Issue by mx1002** [Twilight0/plugin.video.alphatv.gr#3]
Hello . For some reason this plugin has stop working from yesterday .

**Comment by Twilight0** [comment]
The indexers need update. Will fix when I have spare time.

**Comment by pRieStaKos** [comment]
Any update ?

**Comment by mx1002** [comment]
Nothing new yet (still does not work)

Στις Δευ, 15 Οκτ 2018 στις 1:12 π.μ., ο/η John Priestakos <
notifications@github.com> έγραψε:

**Comment by pRieStaKos** [comment]
Pump ?

**Comment by Twilight0** [comment]
Addon has been updated, issue is being closed.
