### ISSUE TITLE
Show Load Time

### ISSUE THREAD

**Issue by pRieStaKos** [Twilight0/plugin.video.alphatv.gr#4]
I'm using LibreElec and Alpha player is taking a long time to load a tv show or freezes, after I choose the show. It loads only if I reboot.

I think this is because it's trying to load all the episodes in one list.

Should be splitting the series in season folders to speed up a bit ?  

- Raspberry Pi4 4GB
- LibreELEC 9.2.3 (Leia)
- Kodi v18.7 (Leia)

**Comment by Twilight0** [comment]
Please specify the show you 're trying to load, otherwise I don't know where to look for.

**Comment by pRieStaKos** [comment]
- Έλα στη θέση μου
- Μην αρχίζεις την μουρμούρα

and every show that got more than 2 seasons (or above 70 episodes).

**Comment by Twilight0** [comment]
There is no need to reboot your box, its going to load, just a little longer. I will add dynamic indexers with a switch on all addons at some point starting from AliveGR.

**Comment by pRieStaKos** [comment]
Just an update on this: 

**Ελα στη θέση μου** has 750 episodes and AlphaTV player takes over 1.5 minute to index the episode list. If you stop an episode and try to go back and play an other, list must load again.

You can see at their site that episodes can be separated to Year (seasons) and make the list load faster. ![image](https://user-images.githubusercontent.com/4584686/95017225-de3b7e00-0660-11eb-971e-61e4b5cbb1d4.png)

Is there any plan for this fix any time soon ?

**Comment by Twilight0** [comment]
Feature implemented on version 2.2.0, issue closed.
