### ISSUE TITLE
3 shows don't open

### ISSUE THREAD

**Issue by kimondiomis94** [Twilight0/plugin.video.alphatv.gr#5]
Hi i love your project and helps a lot on my daily entertainment. There is only one issue with the alphatv player and this issue has been there for couples of months now. There are three shows that don't even open, meaning their episodes don't populate, these shows are the following:
-DEAL 
-HAPPY` DAY ΣΤΟΝ ALPHA
-ΣΑΒΒΑΤΟΚΥΡΙΑΚΟ ΜΕ ΤΟΝ ΜΑΝΕΣΗ

**Comment by Twilight0** [comment]
Fixed in 2.3.2 version.

**Comment by kimondiomis94** [comment]
❤️😊
